version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: map_app
    ports:
      - "80:3000"

  db:
    build:
      context: ./develop/postgres/
      dockerfile: Dockerfile
    restart: always
    container_name: map_db
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
    ports:
      - "${PG_EXTERNAL_PORT}"
    volumes:
      - $PG_DATA_VOLUMES

volumes:
  database:
    driver: local

